CREATE TABLE [dbo].[ELDOPFLPENDLINES] (
    [POLICY_UNDERWRITER]               VARCHAR (3)     NULL,
    [GROUP_NUMBER]                     VARCHAR (3)     NULL,
    [CLAIM_NUMBER]                     VARCHAR (11)    NULL,
    [EMPLOYEE_SSN]                     VARCHAR (9)     NULL,
    [BENEFIT_CODE]                     VARCHAR (3)     NULL,
    [FROM_DATE_OF_SERVICE]             DATE            NULL,
    [THRU_DATE_OF_SERVICE]             DATE            NULL,
    [BENEFIT_AMOUNT]                   DECIMAL (11, 2) NULL,
    [BENEFIT_REASON]                   VARCHAR (2)     NULL,
    [FICA_FROM_DATE]                   DATE            NULL,
    [FICA_THRU_DATE]                   DATE            NULL,
    [FICA_AMOUNT]                      DECIMAL (11, 2) NULL,
    [FICA_REASON]                      VARCHAR (2)     NULL,
    [OFFSET_FROM_DATE]                 DATE            NULL,
    [OFFSET_THRU_DATE]                 DATE            NULL,
    [OFFSET_AMOUNT]                    DECIMAL (11, 2) NULL,
    [OFFSET_REASON]                    VARCHAR (2)     NULL,
    [WITHHOLDINGS_FROM_DATE]           DATE            NULL,
    [WITHHOLDINGS_THRU_DATE]           DATE            NULL,
    [WITHHOLDINGS_FLAT_DOLLAR_PERCENT] VARCHAR (1)     NULL,
    [WITHHOLDINGS_PERCENT]             VARCHAR (6)     NULL,
    [WITHHOLDINGS_AMOUNT]              DECIMAL (11, 2) NULL,
    [WITHHOLDINGS_REASON]              VARCHAR (2)     NULL,
    [OTHER_FROM_DATE_1]                DATE            NULL,
    [OTHER_FROM_DATE_2]                DATE            NULL,
    [OTHER_FROM_DATE_3]                DATE            NULL,
    [OTHER_FROM_DATE_4]                DATE            NULL,
    [OTHER_THRU_DATE_1]                DATE            NULL,
    [OTHER_THRU_DATE_2]                DATE            NULL,
    [OTHER_THRU_DATE_3]                DATE            NULL,
    [OTHER_THRU_DATE_4]                DATE            NULL,
    [OTHER_AMOUNT_1]                   DECIMAL (11, 2) NULL,
    [OTHER_AMOUNT_2]                   DECIMAL (11, 2) NULL,
    [OTHER_AMOUNT_3]                   DECIMAL (11, 2) NULL,
    [OTHER_AMOUNT_4]                   DECIMAL (11, 2) NULL,
    [OTHER_REASON_1]                   VARCHAR (2)     NULL,
    [OTHER_REASON_2]                   VARCHAR (2)     NULL,
    [OTHER_REASON_3]                   VARCHAR (2)     NULL,
    [OTHER_REASON_4]                   VARCHAR (2)     NULL,
    [OTHER_TAX_AMT_1]                  VARCHAR (1)     NULL,
    [OTHER_TAX_AMT_2]                  VARCHAR (1)     NULL,
    [OTHER_TAX_AMT_3]                  VARCHAR (1)     NULL,
    [OTHER_TAX_AMT_4]                  VARCHAR (1)     NULL,
    [COVERED_PAID_DAYS]                VARCHAR (4)     NULL,
    [PAYMENT_AMOUNT]                   DECIMAL (11, 2) NULL,
    [NOT_CURRENTLY_USED]               DECIMAL (11, 2) NULL,
    [PAID_TO_EMPLOYEE]                 DECIMAL (11, 2) NULL,
    [SSN_DEDUCTIONS]                   DECIMAL (11, 2) NULL,
    [MEDICARE_DEDUCTIONS]              DECIMAL (11, 2) NULL,
    [ROLLOVER_OCCURED]                 VARCHAR (1)     NULL,
    [INELIG_AMT_FROM_ADJ]              DECIMAL (11, 2) NULL,
    [ACCUM_EXCEPTION_BUCKET]           VARCHAR (2)     NULL,
    [OTHER_ACCUM_AMT_NUMBER_USED_1]    VARCHAR (1)     NULL,
    [OTHER_ACCUM_AMT_NUMBER_USED_2]    VARCHAR (1)     NULL,
    [OTHER_ACCUM_AMT_NUMBER_USED_3]    VARCHAR (1)     NULL,
    [OTHER_ACCUM_AMT_NUMBER_USED_4]    VARCHAR (1)     NULL,
    [SSN_WAGES]                        DECIMAL (11, 2) NULL,
    [MEDICARE_WAGES]                   DECIMAL (11, 2) NULL,
    [FICA_WAGES]                       DECIMAL (11, 2) NULL,
    [LOAD_DATE]                        DATE            CONSTRAINT [ELDOPFLPENDLINES_LOAD_DATE] DEFAULT (getdate()) NULL
);


GO
CREATE NONCLUSTERED INDEX [ELDOPFLPENDLINES_IDX]
    ON [dbo].[ELDOPFLPENDLINES]([POLICY_UNDERWRITER] ASC, [GROUP_NUMBER] ASC, [CLAIM_NUMBER] ASC);

