CREATE TABLE [dbo].[ELDOEMPLOYEE] (
    [POLICY_UNDERWRITER_NUMBER]     VARCHAR (3)  NOT NULL,
    [GROUP_NUMBER]                  VARCHAR (3)  NOT NULL,
    [EMPLOYEE_SSN]                  VARCHAR (9)  NOT NULL,
    [DATE_LAST_CHANGED]             DATE         NULL,
    [CHANGE_BY]                     VARCHAR (6)  NULL,
    [EMPLOYEE_CERTIFICATE_NUMBER]   VARCHAR (12) NULL,
    [EMPLOYEE_LAST_NAME]            VARCHAR (15) NULL,
    [EMPLOYEE_FIRST_NAME]           VARCHAR (15) NULL,
    [EMPLOYEE_MIDDLE_INITIAL]       VARCHAR (1)  NULL,
    [EMPLOYEE_NAME_SUFFIX]          VARCHAR (6)  NULL,
    [EMPLOYEE_NAME]                 VARCHAR (30) NULL,
    [ADDRESS_LINE_1]                VARCHAR (30) NULL,
    [ADDRESS_LINE_2]                VARCHAR (30) NULL,
    [CITY]                          VARCHAR (15) NULL,
    [STATE]                         VARCHAR (2)  NULL,
    [ZIP_CODE]                      VARCHAR (9)  NULL,
    [PROCEDURE_LOCATION_CODE]       VARCHAR (3)  NULL,
    [HOME_PHONE_NUMBER]             VARCHAR (10) NULL,
    [WORK_PHONE_NUMBER]             VARCHAR (10) NULL,
    [DEPARTMENT_NUMBER]             VARCHAR (8)  NULL,
    [SEX]                           VARCHAR (1)  NULL,
    [DATE_OF_BIRTH]                 DATE         NULL,
    [HIRED_DATE]                    DATE         NULL,
    [DATE_OF_FIRST_ENROLLMENT]      DATE         NULL,
    [LEAVING_REASON]                VARCHAR (1)  NULL,
    [LAST_BILLING_DATE]             DATE         NULL,
    [NUMBER_OF_DEPENDENTS]          VARCHAR (2)  NULL,
    [NUMBER_OF_DEPENDENTS_ON_FILE]  VARCHAR (2)  NULL,
    [XTRA_1]                        VARCHAR (1)  NULL,
    [SPECIAL_CODES]                 VARCHAR (10) NULL,
    [NOTES_1]                       VARCHAR (40) NULL,
    [NOTES_2]                       VARCHAR (40) NULL,
    [BENEFICIARY_NAME]              VARCHAR (30) NULL,
    [LIFETIME_PENSION_CREDITS]      VARCHAR (5)  NULL,
    [PENSION_YR_LFTIME_CR]          VARCHAR (2)  NULL,
    [XTRA_2]                        VARCHAR (1)  NULL,
    [PREMIUMS_PAID_UNTIL]           DATE         NULL,
    [PCS_CARD_SELECT]               VARCHAR (1)  NULL,
    [PCS_CARD_REASON]               VARCHAR (2)  NULL,
    [PCS_CARD_COMPLETE_DATE]        DATE         NULL,
    [TAKE_OVER_STATUS]              VARCHAR (1)  NULL,
    [MEDICALLY_UNDERWRITTEN]        VARCHAR (1)  NULL,
    [COBRA_RECORD_FOR_EMPLOYEE]     VARCHAR (1)  NULL,
    [MARIED_OR_SINGLE]              VARCHAR (1)  NULL,
    [DATE_MARRIED]                  DATE         NULL,
    [ID_CARD_SELECT]                VARCHAR (1)  NULL,
    [ID_CARD_FORMAT]                VARCHAR (12) NULL,
    [ID_CARD_RUN_DATE]              DATE         NULL,
    [LABEL_SELECT]                  VARCHAR (1)  NULL,
    [LABEL_FORMAT]                  VARCHAR (12) NULL,
    [LABEL_RUN_DATE]                DATE         NULL,
    [CERTIFICATE_SELECT]            VARCHAR (1)  NULL,
    [CERTIFICATE_CARD_FORMAT]       VARCHAR (12) NULL,
    [CERTIFICATE_RUN_DATE]          DATE         NULL,
    [NUMBER_CHECKS_WRITTEN]         VARCHAR (6)  NULL,
    [DOLLAR_VALUE_OF_CHECKS]        VARCHAR (12) NULL,
    [RPE_ID]                        VARCHAR (3)  NULL,
    [RPE_MASTER_ID]                 VARCHAR (8)  NULL,
    [CONVERTED_EE]                  VARCHAR (1)  NULL,
    [PD_THRU_DATE]                  DATE         NULL,
    [EXPEDITE_CLAIM]                VARCHAR (1)  NULL,
    [FINANCIAL_CATEGORY]            VARCHAR (2)  NULL,
    [MEDICARE_INDICATOR]            VARCHAR (1)  NULL,
    [HCRA_COUNTY]                   VARCHAR (20) NULL,
    [HIPAA_CERTIFICATE_SELECT]      VARCHAR (1)  NULL,
    [HIPAA_CERTIFICATE_CARD_FORMAT] VARCHAR (12) NULL,
    [HIPAA_CERTIFICATE_RUN_DATE]    DATE         NULL,
    [HCRA_EFF_DATE]                 DATE         NULL,
    [LAST_UPDATE_DATE]              DATE         NULL,
    [LAST_UPDATE_USER]              VARCHAR (20) NULL,
    [LOAD_DATE]                     DATE         CONSTRAINT [ELDOEMPLOYEE_LOAD_DATE] DEFAULT (getdate()) NULL,
    [LAST_UPDATE_TIME]              DATETIME     CONSTRAINT [ELDOEMPLOYEE_LAST_UPDATE_TIME] DEFAULT (getdate()) NULL,
    [EMP_HANDICAP]                  CHAR (1)     NULL,
    [EMP_FILLER]                    VARCHAR (22) NULL,
    [FSA_CARD]                      VARCHAR (1)  NULL,
    [FSA_DATE_EXTRACTED]            DATE         NULL,
    [LFSA_CARD]                     VARCHAR (1)  NULL,
    [LFSA_DATE_EXTRACTED]           DATE         NULL,
    [HRA_CARD]                      VARCHAR (1)  NULL,
    [HRA_DATE_EXTRACTED]            DATE         NULL,
    [EMP_ALTID1]                    VARCHAR (20) NULL,
    [EMP_ALTID2]                    VARCHAR (20) NULL,
    CONSTRAINT [PKELDOEMPLOYEE] PRIMARY KEY CLUSTERED ([POLICY_UNDERWRITER_NUMBER] ASC, [GROUP_NUMBER] ASC, [EMPLOYEE_SSN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ELDOECERTPOLUGRPN]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_CERTIFICATE_NUMBER] ASC, [POLICY_UNDERWRITER_NUMBER] ASC, [GROUP_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPBDATE]
    ON [dbo].[ELDOEMPLOYEE]([DATE_OF_BIRTH] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPCERTNO]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_CERTIFICATE_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPGRPUNDW]
    ON [dbo].[ELDOEMPLOYEE]([POLICY_UNDERWRITER_NUMBER] ASC, [GROUP_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPLOADDT]
    ON [dbo].[ELDOEMPLOYEE]([LOAD_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPLOYEE_LNAME]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_LAST_NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPNAME]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_FIRST_NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPPGEDPT]
    ON [dbo].[ELDOEMPLOYEE]([POLICY_UNDERWRITER_NUMBER] ASC, [GROUP_NUMBER] ASC, [EMPLOYEE_SSN] ASC, [DEPARTMENT_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOEMPSSN]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_SSN] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOLASTFIRST]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_LAST_NAME] ASC, [EMPLOYEE_FIRST_NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOLASTFIRSTSSN]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_LAST_NAME] ASC, [DATE_OF_BIRTH] ASC, [EMPLOYEE_FIRST_NAME] ASC, [GROUP_NUMBER] ASC, [POLICY_UNDERWRITER_NUMBER] ASC, [EMPLOYEE_SSN] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOLASTFIRSTPCNSSN]
    ON [dbo].[ELDOEMPLOYEE]([POLICY_UNDERWRITER_NUMBER] ASC, [DEPARTMENT_NUMBER] ASC, [ZIP_CODE] ASC, [STATE] ASC, [CITY] ASC, [ADDRESS_LINE_2] ASC, [ADDRESS_LINE_1] ASC, [SEX] ASC, [DATE_OF_BIRTH] ASC, [EMPLOYEE_LAST_NAME] ASC, [EMPLOYEE_MIDDLE_INITIAL] ASC, [EMPLOYEE_FIRST_NAME] ASC, [EMPLOYEE_CERTIFICATE_NUMBER] ASC, [EMPLOYEE_SSN] ASC, [GROUP_NUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOSTATESSN]
    ON [dbo].[ELDOEMPLOYEE]([STATE] ASC, [EMPLOYEE_SSN] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOSEPTNUMSEX]
    ON [dbo].[ELDOEMPLOYEE]([DEPARTMENT_NUMBER] ASC, [SEX] ASC, [EMPLOYEE_SSN] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOSSNSEPTNUMSEX]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_SSN] ASC, [DEPARTMENT_NUMBER] ASC, [SEX] ASC);


GO
CREATE NONCLUSTERED INDEX [ELDOSSSTATENSEPTNUMSEX]
    ON [dbo].[ELDOEMPLOYEE]([EMPLOYEE_SSN] ASC, [STATE] ASC, [POLICY_UNDERWRITER_NUMBER] ASC, [GROUP_NUMBER] ASC);

