CREATE TABLE [hsi].[medsystemsettings] (
    [displaynotice]       BIGINT     NULL,
    [medrecreqapprove]    BIGINT     NULL,
    [confnoticetext]      TEXT       NULL,
    [dfcyworkdisttype]    BIGINT     NULL,
    [flags]               BIGINT     NULL,
    [mpicqnum]            BIGINT     NULL,
    [closesrvrinterval]   BIGINT     NULL,
    [maxsuspension]       BIGINT     NULL,
    [printername]         CHAR (100) NULL,
    [epicdfuphl7msgnum]   BIGINT     NULL,
    [epicdfuphl7dstnum]   BIGINT     NULL,
    [epicprovidtype]      CHAR (32)  NULL,
    [rescomplduration]    BIGINT     NULL,
    [transmissingdata]    CHAR (30)  NULL,
    [defdisplaysec]       BIGINT     NULL,
    [flags2]              BIGINT     NULL,
    [maxsearchresults]    BIGINT     NULL,
    [doclistsorttype]     BIGINT     NULL,
    [pininactivetime]     BIGINT     NULL,
    [misfileitemtypenum]  BIGINT     NULL,
    [misfileoverlayit]    BIGINT     NULL,
    [adminusernum]        BIGINT     NULL,
    [doclistpagesize]     BIGINT     NULL,
    [flags3]              BIGINT     NULL,
    [emergencyaccesstime] BIGINT     NULL,
    [docattachmode]       BIGINT     NULL
);

