CREATE TABLE [hsi].[rcmartransaction] (
    [rcmartransactnum]    BIGINT          NOT NULL,
    [originalbatchnum]    BIGINT          NULL,
    [lastbatchnum]        BIGINT          NULL,
    [isprocessed]         BIGINT          NULL,
    [rcmarpatientnum]     BIGINT          NULL,
    [rcmbillingnum]       BIGINT          NULL,
    [rcmfacilitynum]      BIGINT          NULL,
    [rcmhostsystemnum]    BIGINT          NULL,
    [rcmbillingtypenum]   BIGINT          NULL,
    [rcmarguarnum]        BIGINT          NULL,
    [rcmaremployernum]    BIGINT          NULL,
    [rcmaraccttypenum]    BIGINT          NULL,
    [rcmarpattypenum]     BIGINT          NULL,
    [rcmaracctstatnum]    BIGINT          NULL,
    [rcmarpatstatnum]     BIGINT          NULL,
    [rcmarvisittypenum]   BIGINT          NULL,
    [rcmorigfinclsnum]    BIGINT          NULL,
    [rcmcurfinclsnum]     BIGINT          NULL,
    [rcmbillingnumber]    CHAR (40)       NULL,
    [totalcharges]        NUMERIC (15, 2) NULL,
    [accountbalance]      NUMERIC (15, 2) NULL,
    [rcmfinalpatbalance]  NUMERIC (15, 2) NULL,
    [rcmtotalpaid]        NUMERIC (15, 2) NULL,
    [rcmtotalpatpaid]     NUMERIC (15, 2) NULL,
    [rcmtotaladjustment]  NUMERIC (15, 2) NULL,
    [otherinspaid]        NUMERIC (15, 2) NULL,
    [coinsuranceamount]   NUMERIC (15, 2) NULL,
    [deductibleamount]    NUMERIC (15, 2) NULL,
    [registrationdate]    DATETIME        NULL,
    [admitdate]           DATETIME        NULL,
    [dischargedate]       DATETIME        NULL,
    [dateofservicefrom]   DATETIME        NULL,
    [dateofserviceto]     DATETIME        NULL,
    [rcmarmedservice]     CHAR (20)       NULL,
    [olddrgrate]          NUMERIC (15, 2) NULL,
    [olddrgid]            CHAR (4)        NULL,
    [newdrgrate]          NUMERIC (15, 2) NULL,
    [newdrgid]            CHAR (4)        NULL,
    [chartlocation]       CHAR (50)       NULL,
    [expectedreimbamount] NUMERIC (15, 2) NULL,
    [systemdate]          DATETIME        NULL,
    [pttimedeath]         DATETIME        NULL,
    [rcmhospitalsvc]      CHAR (10)       NULL,
    [rcmpatientrep]       CHAR (10)       NULL,
    [rcmcourtesyallow]    CHAR (1)        NULL,
    [rcmoldapc]           CHAR (10)       NULL,
    [rcmnewapc]           CHAR (10)       NULL,
    [abnindicator]        CHAR (50)       NULL,
    [rcmorderdiagnosis]   CHAR (10)       NULL,
    [rcmadmitdiagnosis]   CHAR (10)       NULL,
    [rcmadmittingphysid]  CHAR (60)       NULL,
    [rcmsurgicalphysid]   CHAR (60)       NULL,
    [rcmattendingphysid]  CHAR (60)       NULL,
    [rcmreferringphysid]  CHAR (60)       NULL,
    [rcmpreregistraremp]  CHAR (30)       NULL,
    [rcmregistraremp]     CHAR (30)       NULL,
    [rcmcoderemp]         CHAR (30)       NULL,
    [rcmadmitpriority]    CHAR (10)       NULL,
    [rcmadmitsource]      CHAR (20)       NULL,
    [abstractcompdate]    DATETIME        NULL,
    [rcmpmtplantype]      CHAR (5)        NULL,
    [lastpatpaydate]      DATETIME        NULL,
    [lastinspaydate]      DATETIME        NULL,
    [finalbilldate]       DATETIME        NULL,
    [origbilldate]        DATETIME        NULL,
    [zerobalancedate]     DATETIME        NULL,
    [collectionfwddate]   DATETIME        NULL,
    [rcmarcolagency]      CHAR (30)       NULL,
    [rcmunitnumber]       CHAR (10)       NULL,
    [rcmarplancode]       CHAR (10)       NULL,
    [rcmargroupcode]      CHAR (10)       NULL,
    [rcmauthnumber]       CHAR (20)       NULL,
    [rcmauthdate]         DATETIME        NULL,
    [rcmautheffstart]     DATETIME        NULL,
    [rcmautheffend]       DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [rcmartransaction1]
    ON [hsi].[rcmartransaction]([rcmartransactnum] ASC);

