-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[getMedicalClaimServiceLines]
	-- Add the parameters for the stored procedure here
	 (@CLAIMNO varchar(60),
	 @GROUPNO varchar(60),
	  @POLICYNO varchar(60))
AS
BEGIN

SELECT * FROM (	
SELECT X.BENEFIT_CODE,CHARGE_AMOUNT,[FROM_DATE_OF_SERVICE],[THRU_DATE_OF_SERVICE],
CASE WHEN CHARGE_AMOUNT>INELIGIBLE_AMOUNT THEN CHARGE_AMOUNT - OVER_USUAL_CUSTOMARY - INELIGIBLE_AMOUNT -DISCOUNT_AMOUNT
 ELSE 0 END AS ALLOWED_CHARGES,[PAYMENT_AMOUNT],'' PROCEDUREID,[PROCEDURE_CODE] 
  , '' PROVIDERID FROM 
DBO.ELDOCLMSLINES X
 WHERE POLICY_UNDERWRITER = @POLICYNO AND --'972' AND
GROUP_NUMBER = @GROUPNO AND --'TUR' AND
CLAIM_NUMBER =@CLAIMNO --'22214995707'
UNION
SELECT X.BENEFIT_CODE,CHARGE_AMOUNT,[FROM_DATE_OF_SERVICE],[THRU_DATE_OF_SERVICE],
CASE WHEN CHARGE_AMOUNT>INELIGIBLE_AMOUNT THEN CHARGE_AMOUNT - OVER_USUAL_CUSTOMARY - INELIGIBLE_AMOUNT -DISCOUNT_AMOUNT
 ELSE 0 END AS ALLOWED_CHARGES,[PAYMENT_AMOUNT],'' PROCEDUREID,[PROCEDURE_CODE] 
  , '' PROVIDERID FROM 
DBO.ELDOPENDCLMSLINES X
 WHERE POLICY_UNDERWRITER = @POLICYNO AND --'972' AND
GROUP_NUMBER = @GROUPNO AND --'TUR' AND
CLAIM_NUMBER =@CLAIMNO --'22214995707'
UNION
SELECT  '' AS BENEFIT_CODE, CHARGE_AMT AS CHARGE_AMOUNT,DATE_FROM AS [FROM_DATE_OF_SERVICE],DATE_TO AS [THRU_DATE_OF_SERVICE],
 0 AS ALLOWED_CHARGES,0 AS [PAYMENT_AMOUNT], '' AS PROCEDUREID,HCPCS_PROCEDURE AS [PROCEDURE_CODE], '' PROVIDER_ID
FROM DBO.ELDOMCSCLMLINES 
WHERE CLAIM_NO = @CLAIMNO --'22214995707'
) A 
ORDER BY A.[FROM_DATE_OF_SERVICE]

END
