CREATE TABLE [hsi].[roisystemsettings] (
    [costperpage]       BIGINT     NULL,
    [freepatientpages]  BIGINT     NULL,
    [patientidmethod]   BIGINT     NULL,
    [printflags]        BIGINT     NULL,
    [printbeginsource]  BIGINT     NULL,
    [printendsource]    BIGINT     NULL,
    [filetypeflags]     BIGINT     NULL,
    [billingflags]      BIGINT     NULL,
    [billitemtypenum]   BIGINT     NULL,
    [billrequestorkt]   BIGINT     NULL,
    [billpatientkt]     BIGINT     NULL,
    [billtotalamountkt] BIGINT     NULL,
    [billrequestkt]     BIGINT     NULL,
    [shipoverlaynum]    BIGINT     NULL,
    [itemtypenamekt]    BIGINT     NULL,
    [flags]             BIGINT     NULL,
    [billformatnum]     BIGINT     NULL,
    [coverformatnum]    BIGINT     NULL,
    [inventoryfmtnum]   BIGINT     NULL,
    [billrequestdatekt] BIGINT     NULL,
    [printitemtypenum]  BIGINT     NULL,
    [tocoverlay]        BIGINT     NULL,
    [roirequestnumkt]   BIGINT     NULL,
    [wcalnum]           BIGINT     NULL,
    [roipatientidtitle] CHAR (100) NULL,
    [rejectitemtypenum] BIGINT     NULL,
    [rejectrequestkt]   BIGINT     NULL,
    [phonemask]         CHAR (51)  NULL,
    [staticstring]      CHAR (151) NULL
);

