CREATE TABLE [hsi].[systemtableex] (
    [mailmaxattachsize]    BIGINT     NULL,
    [flags]                BIGINT     NULL,
    [loginitemnum]         BIGINT     NULL,
    [workweekflags]        BIGINT     NULL,
    [dateformat]           BIGINT     NULL,
    [dateseparator]        BIGINT     NULL,
    [verityversion]        BIGINT     NULL,
    [severityflag]         BIGINT     NULL,
    [defusertmplnum]       BIGINT     NULL,
    [ugcopyflags]          BIGINT     NULL,
    [flags2]               BIGINT     NULL,
    [autoauthflags]        BIGINT     NULL,
    [dtgapplydefault]      BIGINT     NULL,
    [internalcustid]       CHAR (20)  NULL,
    [licensehash]          CHAR (255) NULL,
    [loglocale]            BIGINT     NULL,
    [pswdpolicynum]        BIGINT     NULL,
    [keypart]              CHAR (25)  NULL,
    [kekflags]             BIGINT     NULL,
    [flags3]               BIGINT     NULL,
    [flags4]               BIGINT     NULL,
    [adusernameattr]       CHAR (25)  NULL,
    [pinpolicynum]         BIGINT     NULL,
    [encsysid]             CHAR (255) NULL,
    [deftextencoding]      BIGINT     NULL,
    [svcacctpolicynum]     BIGINT     NULL,
    [pswdcompat]           BIGINT     NULL,
    [captchasitekey]       CHAR (255) NULL,
    [captchasecret]        CHAR (255) NULL,
    [idfileencoding]       BIGINT     NULL,
    [adhocimportsizelimit] BIGINT     NULL,
    [flags5]               BIGINT     NULL,
    [updatefileflag1]      BIGINT     NULL,
    [updatefileflag2]      BIGINT     NULL
);

