CREATE TABLE [hsi].[systemtable] (
    [maxpendbackups]   BIGINT     NULL,
    [maxqitems]        BIGINT     NULL,
    [diskidname]       CHAR (12)  NOT NULL,
    [itfileversionnum] BIGINT     NULL,
    [updatefileflag1]  BIGINT     NULL,
    [updatefileflag2]  BIGINT     NULL,
    [updatefileflag3]  BIGINT     NULL,
    [updatefileflag4]  BIGINT     NULL,
    [wfdefimagenum]    BIGINT     NULL,
    [wfdeftextnum]     BIGINT     NULL,
    [liteloadpath]     CHAR (255) NULL,
    [exeupdatepath]    CHAR (255) NULL,
    [exeupdate]        BIGINT     NULL,
    [exeupdateflags]   BIGINT     NULL,
    [ftwebsite]        CHAR (250) NULL,
    [dosinterface]     BIGINT     NULL,
    [fatpartitionname] CHAR (50)  NULL,
    [maxbadlogins]     BIGINT     NULL,
    [defaultdbspace]   CHAR (60)  NULL,
    [tempdbspace]      CHAR (60)  NULL,
    [flags]            BIGINT     NULL,
    [definstitution]   BIGINT     NULL,
    [passworddllpath]  CHAR (255) NULL,
    [errorlogfile]     CHAR (255) NULL,
    [centurypivotyear] BIGINT     NULL,
    [passwordhash]     CHAR (255) NULL,
    [slowqueryminimum] BIGINT     NULL
);

