CREATE TABLE [hsi].[terminalprefs] (
    [blink]              BIGINT NULL,
    [blinkbright]        BIGINT NULL,
    [blinkbrightreverse] BIGINT NULL,
    [blinkbrightul]      BIGINT NULL,
    [blinkbrightulrev]   BIGINT NULL,
    [blinkreverse]       BIGINT NULL,
    [blinkulreverse]     BIGINT NULL,
    [blinkunderline]     BIGINT NULL,
    [bright]             BIGINT NULL,
    [brightreverse]      BIGINT NULL,
    [brightulreverse]    BIGINT NULL,
    [brightunderline]    BIGINT NULL,
    [bufferlines]        BIGINT NULL,
    [columns]            BIGINT NULL,
    [cursorblink]        BIGINT NULL,
    [cursorsize]         BIGINT NULL,
    [functionkeys]       BIGINT NULL,
    [ibmtoansi]          BIGINT NULL,
    [inboundcrlf]        BIGINT NULL,
    [lines]              BIGINT NULL,
    [linewrap]           BIGINT NULL,
    [localecho]          BIGINT NULL,
    [normal]             BIGINT NULL,
    [normalreverse]      BIGINT NULL,
    [outboundcrlf]       BIGINT NULL,
    [scrollbars]         BIGINT NULL,
    [sound]              BIGINT NULL,
    [translation]        BIGINT NULL,
    [underline]          BIGINT NULL,
    [underlinereverse]   BIGINT NULL
);

